### PR TITLE
Update of simulator documentation 

### PR DESCRIPTION
**Pull request by peterlacis**
As the structure of the simulator block moved away from the "generator/trigger" explanation intended more for block construction, this documentation has been updated to correspond with the current state of the 5 simulator blocks available as of the writing of this.

### CODE REVIEW

**Comment by hansmosh** [comment]
@peterlacis I'm going to request that you squash all these commits into one in order to keep the commit history clean. A nice simple example is shown here:
http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html

You'll just want to `git rebase -i HEAD~12`. Then change everything except the first line form 'pick' to 'squash' (or just 's' for short). You'll either need to then force push to your remote (which is ok in this case) or push to a new remote branch and then make a new PR from that one. 

Let me know if you have any questions and I can walk you through this very quickly. Thanks.

**Comment by hansmosh** [comment]
Actually, I'm not sure that I agree with the new format for this readme. The reason why we don't have every block specifically documented is because every block is really just "one Generator and one or more Triggers" as specified in the existing docs. So as long as you can look at the docs for you Generator and Triggers, then the docs for the specific block can be inferred from that.

The idea is that you can add one new Trigger and add it to X Generators to make X new blocks. With this new doc format, you would also need to add docs for X blocks, where with the existing doc format you just need to document your new Trigger. 

At the very least, the explanation about Generators and Triggers needs to stay. Instead of removing that and adding new docs for each block, we could just add docs for some of the more common blocks.

**Comment by peterlacis** [comment]
@hansmosh - I hear what you are saying.  I suppose the issue at hand is who the intended audience is for this documentation.  I agree that it is important for developers that are creating new blocks to see the generator/trigger documentation.  That said, as a user of n.io (not a developer), I found this section of the documentation much more difficult to get through because it didn't line up directly with the blocks that were available (like all the other block documentation does).  So from a format standpoint, how would you suggest we present the information so that the bigger concepts are covered (e.g. generator/trigger) while still clearly defining each of the blocks that are currently available?

**Comment by mattdodge** [comment]
The documentation should target both audiences. Therefore, we definitely don't want to delete the existing documentation, which is very important for developers. 

Perhaps the best thing to do is have a section of blocks that talks (in a more brief manner) about how this combination works and has a list of the included blocks. These blocks could have a brief description and then link to more thorough documentation with their respective trigger/generator.

**Comment by hansmosh** [comment]
Matt's suggestion sounds good to me.

- Keep the developer documentation for explaining what Triggers and Generators are
- Also keep the documentation for each Trigger and Generator.
- Add a "Blocks" section to the top of the README that has a short description of what each block does. Each block links to the Trigger(s) and Generator docs that make it up. 
- Rename the existing "Blocks" section to "Creating Blocks" or something to that effect

**Comment by hansmosh** [comment]
@peterlacis: While I agree that the documentation could be updated to be more user friendly (as opposed to developer friendly), this PR removes too much of the developer documentation (i.e. trigger and generator docs). I'm closing this PR and a new one can be created when it is ready.

**Pull request closed without merging**
