### PR TITLE
cleans up the fast generator

### PR DESCRIPTION
**Pull request by mattdodge**

### CODE REVIEW

**Comment by mattdodge** [comment]
Keeping this open as I think it's still cleaner and I saw better performance. Not going to merge until the restarting count bug is fixed in it though

**Comment by cloudformdesign** [comment]
I think something like that could work if you made the first and the last indexes the correct value. Essentially that's what mine does.

**Comment by hansmosh** [comment]
@mattdodge Are we cool with closing this or is there something we want from it?

**Comment by mattdodge** [comment]
@hansmosh Keep it open, I want to switch over to this method but there's still one bug I need to fix with it

**Comment by mattdodge** [comment]
Ok, this can be closed, a better PR (#26) has been submitted.

**Pull request closed without merging**
